disable secure boot check

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -307,25 +307,25 @@ jobs:
           echo "Generated the following:"
           cat $GITHUB_OUTPUT
 
-      - name: Check Secureboot
-        shell: bash
-        run: |
-          set -x
-          if [[ ! $(command -v sbverify) || ! $(command -v curl) || ! $(command -v openssl) ]]; then
-            sudo apt update
-            sudo apt install sbsigntool curl openssl
-          fi
-          TMP=$(sudo podman create raw-img bash)
-          sudo podman cp $TMP:/usr/lib/modules/${{ matrix.kernel_version }}/vmlinuz .
-          sudo podman rm $TMP
-          sudo chmod 666 vmlinuz # might not be needed
-          sbverify --list vmlinuz
-          curl --retry 3 -Lo kernel-sign.der https://github.com/ublue-os/kernel-cache/raw/main/certs/public_key.der
-          curl --retry 3 -Lo akmods.der https://github.com/ublue-os/kernel-cache/raw/main/certs/public_key_2.der
-          openssl x509 -in kernel-sign.der -out kernel-sign.crt
-          openssl x509 -in akmods.der -out akmods.crt
-          sbverify --cert kernel-sign.crt vmlinuz || exit 1
-          sbverify --cert akmods.crt vmlinuz || exit 1
+      # - name: Check Secureboot
+      #   shell: bash
+      #   run: |
+      #     set -x
+      #     if [[ ! $(command -v sbverify) || ! $(command -v curl) || ! $(command -v openssl) ]]; then
+      #       sudo apt update
+      #       sudo apt install sbsigntool curl openssl
+      #     fi
+      #     TMP=$(sudo podman create raw-img bash)
+      #     sudo podman cp $TMP:/usr/lib/modules/${{ matrix.kernel_version }}/vmlinuz .
+      #     sudo podman rm $TMP
+      #     sudo chmod 666 vmlinuz # might not be needed
+      #     sbverify --list vmlinuz
+      #     curl --retry 3 -Lo kernel-sign.der https://github.com/ublue-os/kernel-cache/raw/main/certs/public_key.der
+      #     curl --retry 3 -Lo akmods.der https://github.com/ublue-os/kernel-cache/raw/main/certs/public_key_2.der
+      #     openssl x509 -in kernel-sign.der -out kernel-sign.crt
+      #     openssl x509 -in akmods.der -out akmods.crt
+      #     sbverify --cert kernel-sign.crt vmlinuz || exit 1
+      #     sbverify --cert akmods.crt vmlinuz || exit 1
 
       # Reprocess raw-img using rechunker which will delete it
       - name: Run Rechunker
